# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3"

networks:
  test:
    external:
      name: test

services:
  ca_root:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    image: hyperledger/fabric-ca:1.5.2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-root
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /root/fabric-setup/network/fabric-ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_root
    networks:
       test:
         aliases:
          - ca.fabric.com
